### PR TITLE
Improvement

### PR DESCRIPTION
**Pull request by Prajwal38**
Plz accept my pull req

Fixes # .

Changes proposed in this pull request:
-
-
-

@pgRouting/admins

### CODE REVIEW

**Comment by Prajwal38** [comment]
Plz do it

**Review by hugovk — CHANGES_REQUESTED** [review]
@Prajwal38 Please do not create yet another spam PR for Hacktoberfest, it's against the rules and values, and not fair on other maintainers.

https://hacktoberfest.digitalocean.com/

Maintainers: Please apply an `invalid` label to this PR so it doesn't count to Hacktoberfest.

**Comment by dkastl** [comment]
As mentioned this pull request is likely to be spam and just steals everyone's time. I'm not sure how to report this to the organizers of Hacktoberfest, but I think users like @Prajwal38 should get banned.

**Comment by hugovk** [comment]
I've asked the organisers: https://twitter.com/hugovk/status/1311339992040566790

**Pull request closed without merging**
